package com.serosoft.academiassu.Helpers;

public interface Permissions {

    String MODULE_PERMISSION = "module_permission";

    //Student Module Permissions
    int STUDENT_PERMISSION_MY_COURSE_VIEW = 9559;
    int STUDENT_PERMISSION_ATTENDANCE_VIEW = 9020;
    int STUDENT_PERMISSION_FEES_VIEW = 9021;
    int STUDENT_PERMISSION_FEES_INVOICE_MAKEPAYMENT = 9028;
    int STUDENT_PERMISSION_ASSIGNMENT_VIEW = 9029;
    int STUDENT_PERMISSION_ASSIGNMENT_HOMEWORK_VIEW = 9030;
    int STUDENT_PERMISSION_ASSIGNMENT_HOMEWORK_SUBMIT = 9031;
    int STUDENT_PERMISSION_ASSIGNMENT_SESSION_DIARY_VIEW = 9032;
    int STUDENT_PERMISSION_RESULT_VIEW = 9033;
    int STUDENT_PERMISSION_EVENTS_VIEW = 9034;
    int STUDENT_PERMISSION_TIMETABLE_VIEW = 9035;
    int STUDENT_PERMISSION_CIRCULARS_VIEW = 9036;
    int STUDENT_PERMISSION_GALLERY_VIEW = 9037;
    int STUDENT_PERMISSION_PDF_DOWNLOAD = 9038;
    int STUDENT_PERMISSION_PROFILE_VIEW = 9383;
    int STUDENT_PERMISSION_PROFILE_PERSONAL_INFORMATION_VIEW = 9384;
    int STUDENT_PERMISSION_PROFILE_PERSONAL_DETAILS_VIEW = 9385;
    int STUDENT_PERMISSION_PROFILE_PARENT_DETAILS_VIEW = 9518;
    int STUDENT_PERMISSION_PROFILE_DOCUMENTS_VIEW = 9386;
    int STUDENT_PERMISSION_PROFILE_PREDEFINED_DOC_VIEW = 9387;
    int STUDENT_PERMISSION_PROFILE_OTHERDOCUMENTS_VIEW = 9388;
    int STUDENT_PERMISSION_PROFILE_OTHER_INFORMATION_VIEW = 9389;
    int STUDENT_EXAMINATION_RESULT_REPORT_VIEW = 9456;
    int STUDENT_EXAMINATION_EXAM_DOCS_VIEW = 9457;
    int STUDENT_EXAMINATION_MARKSHEET_VIEW = 9458;
    int STUDENT_EXAMINATION_HALLTICKET_VIEW = 9459;
    int STUDENT_RATE_AND_REVIEW_VIEW = 9569;
    int STUDENT_FEEDBACK_VIEW = 9570;
    int STUDENT_STAR_RATING_VIEW = 9571;
    int STUDENT_ENTER_FEEDBACK_VIEW = 9572;
    int STUDENT_MY_REQUEST_VIEW = 9653;
    int STUDENT_MEDICAL_CONDITION_VIEW = 9907;
    int STUDENT_MAKE_PAYMENT_VIEW = 9988;
    int STUDENT_DISCIPLINARY_ACTION_VIEW = 10017;
    int STUDENT_FEE_PAYER_DETAILS_VIEW = 10022;

    //Parent Module Permissions
    int PARENT_PERMISSION_MY_COURSE_VIEW = 9558;
    int PARENT_PERMISSION_ATTENDANCE_VIEW = 9039;
    int PARENT_PERMISSION_FEES_VIEW = 9040;
    int PARENT_PERMISSION_FEES_INVOICE_MAKEPAYMENT = 9045;
    int PARENT_PERMISSION_ASSIGNMENT_VIEW = 9048;
    int PARENT_PERMISSION_ASSIGNMENT_HOMEWORK_VIEW = 9049;
    int PARENT_PERMISSION_ASSIGNMENT_HOMEWORK_SUBMIT = 9050;
    int PARENT_PERMISSION_ASSIGNMENT_SESSION_DIARY_VIEW = 9051;
    int PARENT_PERMISSION_RESULT_VIEW = 9052;
    int PARENT_PERMISSION_EVENTS_VIEW = 9053;
    int PARENT_PERMISSION_TIMETABLE_VIEW = 9054;
    int PARENT_PERMISSION_CIRCULARS_VIEW = 9055;
    int PARENT_PERMISSION_GALLERY_VIEW = 9056;
    int PARENT_PERMISSION_PDF_DOWNLOAD = 9057;
    int PARENT_PERMISSION_PROFILE_VIEW = 9390;
    int PARENT_PERMISSION_PROFILE_PERSONAL_INFORMATION_VIEW = 9391;
    int PARENT_PERMISSION_PROFILE_PERSONAL_DETAILS_VIEW = 9392;
    int PARENT_PERMISSION_PROFILE_PARENT_DETAILS_VIEW = 9557;
    int PARENT_PERMISSION_PROFILE_DOCUMENTS_VIEW = 9393;
    int PARENT_PERMISSION_PROFILE_PREDEFINED_DOC_VIEW = 9394;
    int PARENT_PERMISSION_PROFILE_OTHERDOCUMENTS_VIEW = 9395;
    int PARENT_PERMISSION_PROFILE_OTHER_INFORMATION_VIEW = 9396;
    int PARENT_EXAMINATION_RESULT_REPORT_VIEW = 9460;
    int PARENT_EXAMINATION_EXAM_DOCS_VIEW = 9461;
    int PARENT_EXAMINATION_MARKSHEET_VIEW = 9462;
    int PARENT_EXAMINATION_HALLTICKET_VIEW = 9463;
    int PARENT_RATE_AND_REVIEW_VIEW = 9565;
    int PARENT_FEEDBACK_VIEW = 9566;
    int PARENT_STAR_RATING_VIEW = 9567;
    int PARENT_ENTER_FEEDBACK_VIEW = 9568;
    int PARENT_MY_REQUEST_VIEW = 9787;
    int PARENT_MEDICAL_CONDITION_VIEW = 9908;
    int PARENT_MAKE_PAYMENT_VIEW = 9989;
    int PARENT_DISCIPLINARY_ACTION_VIEW = 10018;
    int PARENT_FEE_PAYER_DETAILS_VIEW = 10023;

}
